#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug  4 14:13:20 2022

@author: t
"""

import pandas as pd
import numpy as np 
import scipy.stats as stats







def accuracy(df):
    
    # takes dataframe of trials (generated by taupelidata_to_dataframe.py)
    # calculates basic accuracy
    
    names = df.name.unique()
    types = 'trial_corners_forced'
    typ=types
    df_correct = pd.DataFrame()
    acc = len(df[df.correct==1]) / len(df[((df['correct']==1) | (df['correct']==0))])
    d = {'name': 'total', 'type': typ, 'condition':'all', 'accuracy': acc }
    df_correct = df_correct.append(d,ignore_index=True)
    
    # separate conditions
    conditions = df.condition.unique()
    conditions.sort()

    for con in conditions: 
        acc = len( df[(df.correct == 1) & (df.condition==con)] ) / \
            len(df[  ((df.correct == 1) | (df['correct'] == 0)) & (df.condition==con)    ])
            
        d = {'name': 'total', 'type': typ, 'condition': con, 'accuracy': acc }
        df_correct = df_correct.append(d, ignore_index=True)

    
    for name in names:
        kh_df = df[(df['name'] == name) & (df['type'] == typ)]
        acc = len(kh_df[kh_df.correct == 1]) / \
            len(kh_df[((kh_df['correct'] == 1) | (kh_df['correct'] == 0))])
        d = {'name': name, 'type': typ, 'condition':'all', 'accuracy': acc}
        df_correct = df_correct.append(d, ignore_index=True)



# condition per kh

    for con in conditions: 
     

        for name in names:
            kh_df = df[(df['name'] == name) & (df['type'] == typ)]
            acc = len( kh_df[(kh_df.correct == 1) & (kh_df.condition==con)] ) / \
                len(kh_df[  ((kh_df.correct == 1) | (kh_df['correct'] == 0)) & (kh_df.condition==con)    ])
    

            d = {'name': name, 'type': typ, 'condition': con, 'accuracy': acc }
            df_correct = df_correct.append(d, ignore_index=True)



    return df_correct
    


df_orig = pd.read_csv('taupelidata_corners_pilotit.csv')

df_acc_all = accuracy(df_orig)


# filter trials with particular startposition differences
df_same = df_orig[(np.abs(df_orig.x0)-np.abs(df_orig.x1) == 0)]
df_differ = df_orig[(np.abs(df_orig.x0)-np.abs(df_orig.x1) != 0)]


df_acc_same = accuracy(df_same)
df_acc_differ = accuracy(df_differ)

df_acc_all['startpos same'] = df_acc_same['accuracy']
df_acc_all['startpos differ'] = df_acc_differ['accuracy']

#df_acc_all contains all results, use this to calculate further

# calculate standard deviations etc

df_acc_std = pd.DataFrame()

conditions = df_acc_all.condition.unique()
for con in conditions:
    df_acc_con = df_acc_all[(df_acc_all.condition==con) & (df_acc_all.name!='total')]
    
    
    std_all = df_acc_con['accuracy'].std()
    std_same = df_acc_con['startpos same'].std()
    std_differ = df_acc_con['startpos differ'].std()
    
    # paired ttest
    stats.ttest_rel(df_acc_con['startpos same'], df_acc_con['startpos differ'])
    res = stats.ttest_rel(df_acc_con['startpos same'], df_acc_con['startpos differ'])
    
    d = {'condition':con, 'std_all':std_all, 'std_startpos_same':std_same, 'std_startpos_differ':std_differ,'ttest_p': res.pvalue}
    df_acc_std = df_acc_std.append(d,ignore_index=True)



# # startposition difference

# df_same = df[(np.abs(df.x0)-np.abs(df.x1) == 0)]
# df_differ = df[(np.abs(df.x0)-np.abs(df.x1) != 0)]


# df = df_same
# acc = len(df[df.correct==1]) / len(df[((df['correct']==1) | (df['correct']==0))])
# d = {'name': 'total', 'type': typ, 'accuracy': acc,'starpos':'same' }
# df_correct = df_correct.append(d,ignore_index=True)

# df = df_differ
# acc = len(df[df.correct==1]) / len(df[((df['correct']==1) | (df['correct']==0))])
# d = {'name': 'total', 'type': typ, 'accuracy': acc,'starpos':'differ' }
# df_correct = df_correct.append(d,ignore_index=True)

# # startposition difference per kh 

# df = df_same
# names = df.name.unique()
# types = 'trial_corners_forced'
# typ=types
# df_correct = pd.DataFrame()
# df = df[df['type']==types]

# acc = len(df[df.correct==1]) / len(df[((df['correct']==1) | (df['correct']==0))])
# d = {'name': 'total', 'type': typ, 'accuracy': acc }
# df_correct = df_correct.append(d,ignore_index=True)

# for name in names:
#     kh_df = df[(df['name'] == name) & (df['type'] == typ)]
#     acc = len(kh_df[kh_df.correct == 1]) / \
#         len(kh_df[((kh_df['correct'] == 1) | (kh_df['correct'] == 0))])
#     d = {'name': name, 'type': typ, 'accuracy': acc}
#     df_correct = df_correct.append(d, ignore_index=True)
       
# print(df_correct)

# # separate conditions with same/differ startpos

# conditions = df.condition.unique()
# conditions.sort()

# for con in conditions: 
#     acc = len( df[(df.correct == 1) & (df.condition==con)] ) / \
#         len(df[  ((df.correct == 1) | (df['correct'] == 0)) & (df.condition==con)    ])
        
#     d = {'name': 'total', 'type': typ, 'accuracy': acc, 'condition': con}
#     df_correct = df_correct.append(d, ignore_index=True)
# df_correct_same = df_correct




# # startposition difference per kh 

# df = df_differ
# names = df.name.unique()
# types = 'trial_corners_forced'
# typ=types
# df_correct = pd.DataFrame()
# df = df[df['type']==types]

# acc = len(df[df.correct==1]) / len(df[((df['correct']==1) | (df['correct']==0))])
# d = {'name': 'total', 'type': typ, 'accuracy': acc }
# df_correct = df_correct.append(d,ignore_index=True)

# for name in names:
#     kh_df = df[(df['name'] == name) & (df['type'] == typ)]
#     acc = len(kh_df[kh_df.correct == 1]) / \
#         len(kh_df[((kh_df['correct'] == 1) | (kh_df['correct'] == 0))])
#     d = {'name': name, 'type': typ, 'accuracy': acc}
#     df_correct = df_correct.append(d, ignore_index=True)
       
# print(df_correct)

# # separate conditions with same/differ startpos

# conditions = df.condition.unique()
# conditions.sort()

# for con in conditions: 
#     acc = len( df[(df.correct == 1) & (df.condition==con)] ) / \
#         len(df[  ((df.correct == 1) | (df['correct'] == 0)) & (df.condition==con)    ])
        
#     d = {'name': 'total', 'type': typ, 'accuracy': acc, 'condition': con}
#     df_correct = df_correct.append(d, ignore_index=True)
# df_correct_differ = df_correct


